name: Run My First Workflow
on: 
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  workflow_dispatch: 
  schedule:
    - cron: "0,30 8-18 * * 1-5"
jobs:
  SayHello:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "Hello All!"
      - name: Checkout
        uses: actions/checkout@v7.0.0
